apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ghoster
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ghoster
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50