apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ghost.fullname" $ }}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "ghost.fullname" $ }}
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 50